export const CURRENT_ACCOUNT = "CURRENT_ACCOUNT";
export const METAMASK_STATUS = "METAMASK_STATUS";
export const METAMASK_CONNECT_FUNCTION = "METAMASK_CONNECT_FUNCTION";
export const LOAD = "LOAD";
export const SHOW_LOADER = "SHOW_LOADER";
export const IS_CERAMIC_AUTHENTICATED = "IS_CERAMIC_AUTHENTICATED";
